const systemFont = [
  '-apple-system',
  'BlinkMacSystemFont',
  'Segoe UI',
  'Roboto',
  'Oxygen',
  'Ubuntu',
  'Cantarell',
  'Helvetica Neue',
  'Apple Color Emoji',
  'Segoe UI Emoji',
  'Segoe UI Symbol',
  'Meiryo UI',
  'Arial',
  'sans-serif',
].map((x) => (x.indexOf(' ') < 0 ? x : `'${ x }'`)).join(', ');

export default {
  headline: {
    fontFamily: systemFont,
    fontSize: '1.375rem',
    fontWeight: 'normal',
    letterSpacing: 0,
    lineHeight: '2rem',
  },
  subtitle: {
    fontFamily: systemFont,
    fontSize: '1rem',
    fontWeight: 'normal',
    letterSpacing: 0,
    lineHeight: '1.375rem',
  },
  boldSubtitle: {
    fontFamily: systemFont,
    fontSize: '1rem',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: '1.375rem',
  },
  paragraph: {
    fontFamily: systemFont,
    fontSize: '0.875rem',
    fontWeight: 'normal',
    letterSpacing: 0,
    lineHeight: '1.25rem',
  },
  boldParagraph: {
    fontFamily: systemFont,
    fontSize: '0.875rem',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: '1.25rem',
  },
  caption: {
    fontFamily: systemFont,
    fontSize: '0.75rem',
    fontWeight: 'normal',
    letterSpacing: 0,
    lineHeight: '1rem',
  },
  boldCaption: {
    fontFamily: systemFont,
    fontSize: '0.75rem',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: '1rem',
  },
  micro: {
    fontFamily: systemFont,
    fontSize: '0.625rem',
    fontWeight: '600',
    letterSpacing: '0.2px',
    lineHeight: '0.75rem',
  },
};
