"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.strike = exports.heading = exports.code = exports.paragraph = exports.link = exports.plain = exports.italic = exports.bold = void 0;
var generate = function (type) { return function (value) { return ({ type: type, value: value }); }; };
exports.bold = generate('BOLD');
exports.italic = generate('ITALIC');
exports.plain = generate('PLAIN_TEXT');
exports.link = generate('LINK');
exports.paragraph = generate('PARAGRAPH');
exports.code = generate('CODE');
exports.heading = generate('HEADING');
exports.strike = generate('STRIKE');
exports.inlineCode = generate('INLINE_CODE');
