// flow-typed signature: fbfc591f361ab1592f06c35558fd09d4
// flow-typed version: <<STUB>>/@emotion/hash_v0.8.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/hash/dist/hash.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/hash/dist/hash.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/hash/dist/hash.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/hash/dist/hash.cjs' {
  declare module.exports: any;
}

declare module '@emotion/hash/dist/hash.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/hash/dist/hash.esm' {
  declare module.exports: any;
}

declare module '@emotion/hash/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/hash/dist/hash.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/hash/dist/hash.browser.cjs'>;
}
declare module '@emotion/hash/dist/hash.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/hash/dist/hash.browser.esm'>;
}
declare module '@emotion/hash/dist/hash.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/hash/dist/hash.cjs.dev'>;
}
declare module '@emotion/hash/dist/hash.cjs.js' {
  declare module.exports: $Exports<'@emotion/hash/dist/hash.cjs'>;
}
declare module '@emotion/hash/dist/hash.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/hash/dist/hash.cjs.prod'>;
}
declare module '@emotion/hash/dist/hash.esm.js' {
  declare module.exports: $Exports<'@emotion/hash/dist/hash.esm'>;
}
declare module '@emotion/hash/src/index' {
  declare module.exports: $Exports<'@emotion/hash/src'>;
}
declare module '@emotion/hash/src/index.js' {
  declare module.exports: $Exports<'@emotion/hash/src'>;
}
