// flow-typed signature: e4dbf9b60e4ed33dbe6fb35b1ae31fa1
// flow-typed version: <<STUB>>/@emotion/stylis_v0.8.5/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/stylis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/stylis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/stylis/dist/stylis.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/stylis/dist/stylis.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/stylis/dist/stylis.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/stylis/dist/stylis.cjs' {
  declare module.exports: any;
}

declare module '@emotion/stylis/dist/stylis.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/stylis/dist/stylis.esm' {
  declare module.exports: any;
}

declare module '@emotion/stylis/src' {
  declare module.exports: any;
}

declare module '@emotion/stylis/src/stylis.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/stylis/dist/stylis.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/stylis/dist/stylis.browser.cjs'>;
}
declare module '@emotion/stylis/dist/stylis.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/stylis/dist/stylis.browser.esm'>;
}
declare module '@emotion/stylis/dist/stylis.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/stylis/dist/stylis.cjs.dev'>;
}
declare module '@emotion/stylis/dist/stylis.cjs.js' {
  declare module.exports: $Exports<'@emotion/stylis/dist/stylis.cjs'>;
}
declare module '@emotion/stylis/dist/stylis.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/stylis/dist/stylis.cjs.prod'>;
}
declare module '@emotion/stylis/dist/stylis.esm.js' {
  declare module.exports: $Exports<'@emotion/stylis/dist/stylis.esm'>;
}
declare module '@emotion/stylis/src/index' {
  declare module.exports: $Exports<'@emotion/stylis/src'>;
}
declare module '@emotion/stylis/src/index.js' {
  declare module.exports: $Exports<'@emotion/stylis/src'>;
}
declare module '@emotion/stylis/src/stylis.min.js' {
  declare module.exports: $Exports<'@emotion/stylis/src/stylis.min'>;
}
