version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
