version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-deps:
        dependency-type: "development"
        update-types: 
        - "minor"
        - "patch"
      prod-deps:
        dependency-type: "production"
        update-types: 
        - "minor"
        - "patch"