import { createTheme } from '../../helpers/createTheme';
import colors from '../../tokens/colors';
import dimensions from '../../theme/dimensions';
import typography from '../../theme/typography';


export default createTheme('rcx-input', {
  padding: '0.625rem 0.875rem',
  borderWidth: dimensions.borders.default.width,
  borderRadius: dimensions.borders.default.radius,
  color: colors.dark800,
  iconColor: colors.dark800,
  placeholderColor: colors.dark600,
  backgroundColor: colors.white,
  borderColor: colors.dark500,
  hoverBorderColor: colors.dark600,
  focusBorderColor: colors.blue500,
  focusShadowColor: colors.blue100,
  focusCaretColor: colors.blue500,
  focusIconColor: colors.blue500,
  activeBorderColor: colors.dark600,
  activeCaretColor: colors.dark600,
  activeShadow: 'none',
  disabledBackgroundColor: colors.dark200,
  disabledBorderColor: colors.dark500,
  disabledColor: colors.dark800,
  disabledIconColor: colors.dark500,
  fontFamily: typography.p1.fontFamily,
  fontSize: '0.875rem',
  fontWeight: '500',
  lineHeight: '1.25rem',
  errorColor: colors.red500,
  errorIconColor: colors.red500,
  errorBorderColor: colors.red500,
  errorFocusShadowColor: colors.red100,
  iconSize: '1.25rem',
  iconMarginHorizontal: '1rem',
  iconMarginVertical: '0.75rem',
  labelMargin: '0 0 0.5rem 0',
  labelColor: colors.dark800,
  labelFontFamily: typography.p1.fontFamily,
  labelFontSize: '0.875rem',
  labelFontWeight: 'normal',
  labelLineHeight: '1.25rem',
  labelRequiredColor: colors.red500,
  labelErrorColor: colors.red500,
  helpMargin: '0.25rem 0 0 0',
  helpColor: colors.dark600,
  helpFontSize: '0.875rem',
  helpFontFamily: typography.p1.fontFamily,
  helpFontWeight: 'normal',
  helpLineHeight: '1.25rem',
});
