import type { ArrayOf } from './ArrayOf';

export type PlottingData = {
  over_noise: ArrayOf<number>[];
  tot_noise: ArrayOf<number>[];
  max_noise: ArrayOf<number>[];
  over_SSD: ArrayOf<number>[];
  energy_save: ArrayOf<number>[];
  ers_save: ArrayOf<number>;
  over: ArrayOf<number>[];
  LAMEsfbits: ArrayOf<number>[];
  LAMEmainbits: ArrayOf<number>[];
  LAMEqss: ArrayOf<number>[];
  LAMEsfb_s: ArrayOf<number>[][];
  thr_s: ArrayOf<number>[][];
  xfsf_s: ArrayOf<number>[][];
  en_s: ArrayOf<number>[][];
  thr: ArrayOf<number>[][];
  LAMEsfb: ArrayOf<number>[][];
  xfsf: ArrayOf<number>[][];
  en: ArrayOf<number>[][];
  pcmdata: ArrayOf<number>[];
  energy: ArrayOf<number>[][];
  ers: ArrayOf<number>[];
  xr: Float32Array[][];
  ms_ener_ratio: ArrayOf<number>;
  blocktype: ArrayOf<number>[];
  ms_ratio: ArrayOf<number>;
  pe: ArrayOf<number>[];
  mean_bits: number;
  resvsize: number;
};
