export default {
  statusInfo: '{colors.b200}',
  statusFontOnInfo: '{colors.b600}',
  statusSuccess: '{colors.g200}',
  statusFontOnSuccess: '{colors.g800}',
  statusDanger: '{colors.r200}',
  statusFontOnDanger: '{colors.r800}',
  statusWarning: '{colors.y200}',
  statusFontOnWarning: '{colors.y900}',
  statusWarning2: '{colors.y100}',
  statusFontOnWarning2: '{colors.n800}',
  statusService1: '{colors.o200}',
  statusFontOnService1: '{colors.o800}',
  statusService2: '{colors.p200}',
  statusFontOnService2: '{colors.p600}',
  statusService3: '{colors.p700}',
  statusFontOnService3: '{colors.white}',
  statusBulletOnline: '{colors.g800}',
  statusBulletAway: '{colors.y800}',
  statusBulletBusy: '{colors.r600}',
  statusBulletDisabled: '{colors.o500}',
  statusBulletOffline: '{colors.n700}',
  statusBulletLoading: '{colors.n700}',
};
