import theme from '../../styles/theme';
import colors from '../../tokens/colors';


export default {
  borderWidth: theme.borders.default.width,
  borderRadius: theme.borders.default.radius,
  fontFamily: theme.typography.p1.fontFamily,
  fontWeight: 500,
  height: '2.5rem',
  paddingVertical: '0.5rem',
  paddingHorizontal: '0.875rem',
  fontSize: '0.875rem',
  lineHeight: '1.25rem',
  iconSize: '1rem',
  smallHeight: '2rem',
  smallPaddingVertical: '0.375rem',
  smallPaddingHorizontal: '0.625rem',
  smallFontSize: '0.75rem',
  smallLineHeight: '1rem',
  smallIconSize: '0.75rem',
  basicColor: colors.dark800,
  basicDangerColor: colors.red500,
  basicBackgroundColor: colors.dark300,
  basicHoverBackgroundColor: colors.dark400,
  basicActiveBackgroundColor: colors.dark500,
  basicFocusBackgroundColor: colors.dark300,
  basicFocusBorderColor: colors.dark500,
  basicFocusShadowColor: colors.dark100,
  basicDisabledColor: colors.dark400,
  basicDisabledDangerColor: colors.red100,
  basicDisabledBackgroundColor: colors.dark100,
  primaryColor: colors.white,
  primaryBackgroundColor: colors.blue500,
  primaryDangerBackgroundColor: colors.red500,
  primaryHoverBackgroundColor: colors.blue600,
  primaryDangerHoverBackgroundColor: colors.red600,
  primaryActiveBackgroundColor: colors.blue700,
  primaryDangerActiveBackgroundColor: colors.red700,
  primaryFocusBackgroundColor: colors.blue500,
  primaryDangerFocusBackgroundColor: colors.red500,
  primaryFocusBorderColor: colors.blue700,
  primaryDangerFocusBorderColor: colors.red700,
  primaryFocusShadowColor: colors.blue100,
  primaryDangerFocusShadowColor: colors.red100,
  primaryDisabledBackgroundColor: colors.blue200,
  primaryDangerDisabledBackgroundColor: colors.red200,
};
