import colors from './colors.json';

export const Surface = {
  'background-light': colors.white,
  'background-tint': colors.n100,

  'stroke-extra-light': colors.white,
  'stroke-light': colors.n400,
  'stroke-medium': colors.n600,
  'stroke-dark': colors.n700,
  'stroke-extra-dark': colors.n800,
  'stroke-extra-light-highlight': colors.p200,
  'stroke-highlight': colors.p500,
  'stroke-extra-light-error': colors.d200,
  'stroke-error': colors.d500,

  'surface-light': colors.white,
  'surface-tint': colors.n100,
  'surface-neutral': colors.n400,
  'surface-disabled': colors.n100,
  'surface-hover': colors.n400,
  'surface-info': colors.i200,
  'surface-success': colors.s200,
  'surface-warning': colors.w200,
  'surface-danger': colors.d200,
  'surface-service-1': colors['s1-200'],
  'surface-service-2': colors['s2-200'],

  'text-white': colors.white,
  'text-disabled': colors.n500,
  'text-annotation': colors.n600,
  'text-hint': colors.n700,
  'text': colors.n800,
  'text-titles-labels': colors.n900,
  'text-danger': colors.d600,
  'text-secondary-info': colors.n700,
  'text-on-info': colors.i600,
  'text-on-success': colors.s800,
  'text-on-warning': colors.w900,
  'text-on-danger': colors.d800,
  'text-on-service-1': colors['s1-800'],
  'text-on-service-2': colors['s2-600'],

  'btn-primary': colors.p500,
  'btn-secondary': colors.n400,
  'btn-secondary-danger': colors.n400,
  'btn-danger': colors.d500,
  'btn-hover-primary': colors.p600,
  'btn-hover-secondary': colors.n500,
  'btn-hover-secondary-danger': colors.n500,
  'btn-hover-danger': colors.d600,
  'btn-press-primary': colors.p700,
  'btn-press-secondary': colors.n600,
  'btn-press-secondary-danger': colors.n600,
  'btn-press-danger': colors.d700,
  'btn-focus-primary': colors.p500,
  'btn-focus-secondary': colors.n400,
  'btn-focus-secondary-danger': colors.n400,
  'btn-focus-danger': colors.d500,
  'btn-keyfocus-primary': colors.p500,
  'btn-keyfocus-secondary': colors.n400,
  'btn-keyfocus-secondary-danger': colors.n400,
  'btn-keyfocus-danger': colors.d500,
  'btn-disable-primary': colors.p200,
  'btn-disable-secondary': colors.n300,
  'btn-disable-secondary-danger': colors.n300,
  'btn-disable-danger': colors.d200,

  'btn-on-primary': colors.white,
  'btn-on-secondary': colors.n900,
  'btn-on-secondary-danger': colors.d700,
  'btn-on-danger': colors.white,
  'btn-on-disable': colors.n600,
  'btn-on-secondary-danger-disable': colors.d300,
};
