name: Setup Playwright
description: Setup Playwright for the CI pipeline with caching

runs:
  using: 'composite'

  steps:
    - name: Cache Playwright binaries
      uses: actions/cache@v4
      id: cache-playwright
      with:
        path: |
          ~/.cache/ms-playwright
        # This is the version of Playwright that we are using, if you are willing to upgrade, you should update this.
        key: playwright-${{ runner.arch }}-${{ runner.os }}-1.58.1

    - name: Install Playwright
      shell: bash
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      working-directory: .
      run: npx playwright install --with-deps

    - name: Cache playwright Setup
      uses: actions/cache/save@v4
      if: steps.cache-playwright.outputs.cache-hit != 'true' && always()
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.arch }}-${{ runner.os }}-1.58.1
