import colors from '../tokens/colors';


export default {
  primary: {
    backgroundColor: colors.blue500,
    borderColor: colors.blue500,
    color: colors.white,
    hoverBackgroundColor: colors.blue600,
    hoverBorderColor: colors.blue600,
    activeBackgroundColor: colors.blue700,
    activeBorderColor: colors.blue700,
    focusBackgroundColor: colors.blue500,
    focusBorderColor: colors.blue700,
    focusShadowColor: colors.blue100,
    disabledBackgroundColor: colors.blue200,
    disabledBorderColor: colors.blue200,
    disabledColor: colors.white,
  },
  secondary: {
    backgroundColor: colors.dark300,
    borderColor: colors.dark300,
    color: colors.dark800,
    hoverBackgroundColor: colors.dark400,
    hoverBorderColor: colors.dark400,
    activeBackgroundColor: colors.dark500,
    activeBorderColor: colors.dark500,
    focusBackgroundColor: colors.dark300,
    focusBorderColor: colors.dark500,
    focusShadowColor: colors.dark100,
    disabledBackgroundColor: colors.dark100,
    disabledBorderColor: colors.dark100,
    disabledColor: colors.dark400,
  },
  danger: {
    backgroundColor: colors.red500,
    borderColor: colors.red500,
    color: colors.white,
    hoverBackgroundColor: colors.red600,
    hoverBorderColor: colors.red600,
    activeBackgroundColor: colors.red700,
    activeBorderColor: colors.red700,
    focusBackgroundColor: colors.red500,
    focusBorderColor: colors.red700,
    focusShadowColor: colors.red100,
    disabledBackgroundColor: colors.red200,
    disabledBorderColor: colors.red200,
    disabledColor: colors.white,
  },
  empty: {
    backgroundColor: colors.white,
    borderColor: colors.dark400,
    color: colors.white,
    hoverBackgroundColor: colors.white,
    hoverBorderColor: colors.dark500,
    activeBackgroundColor: colors.white,
    activeBorderColor: colors.dark600,
    focusBackgroundColor: colors.white,
    focusBorderColor: colors.blue500,
    focusShadowColor: colors.blue100,
    disabledBackgroundColor: colors.dark200,
    disabledBorderColor: colors.dark200,
    disabledColor: colors.white,
  },
  off: {
    backgroundColor: colors.dark400,
    borderColor: colors.dark400,
    color: colors.white,
    hoverBackgroundColor: colors.dark500,
    hoverBorderColor: colors.dark500,
    activeBackgroundColor: colors.dark600,
    activeBorderColor: colors.dark600,
    focusBackgroundColor: colors.dark500,
    focusBorderColor: colors.blue500,
    focusShadowColor: colors.blue100,
    disabledBackgroundColor: colors.dark400,
    disabledBorderColor: colors.dark400,
    disabledColor: colors.dark200,
  },
};
