name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.20.0'
          cache: 'yarn'
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.job }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - run: yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run ci
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: 'storybooks-${{ github.event.number }}'
          path: |
            packages/fuselage/storybook-static
            packages/onboarding-ui/storybook-static
            packages/layout/storybook-static
