name: Continuous Delivery Test

on:
  pull_request:
    branches:
      - ci/autoBump

jobs:
  bump-packages:
    name: Bump packages on Rocket.Chat
    runs-on: ubuntu-latest
    # needs:
    #   - publish-to-npm
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "RocketChat/Rocket.Chat"
          # persist-credentials: false
          # fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14.21.3"
      - name: Upgrade packages
        run: yarn up @rocket.chat/fuselage@0.31.0

      - name: Create Pull Request
        # id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          # signoff: false
          branch: example-patches
          delete-branch: true
          title: "[Example] Update report"
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          # labels: |
          #   report
          #   automated pr
          # assignees: peter-evans
          # reviewers: peter-evans
          # team-reviewers: |
          #   developers
          #   qa-team
          # milestone: 1
          # draft: false
